### ISSUE TITLE
Dark theme doesn't autoload

### ISSUE THREAD

**Issue by tostercx** [bousqi/slm-patcher#2]
Setting the dark theme works, but after closing and re-opening slm it's back to light mode.
Going in the preferences the setting still shows current as the dark theme, even tho it's rendering light :<

![image](https://user-images.githubusercontent.com/4965387/46151946-96670c80-c278-11e8-9f99-84377eb9f7c9.png)

Tested on slm 1062 win x64

**Comment by tostercx** [comment]
I found a way to fix it (base addr 7FF63C0E0000)

    00007FF63C1014E0 | 55                       | push rbp                                     |
    00007FF63C1014E1 | 56                       | push rsi                                     | rsi:&"themed_container_control"
    00007FF63C1014E2 | 48 83 EC 28              | sub rsp,28                                   |
    00007FF63C1014E6 | 48 8D 6C 24 20           | lea rbp,qword ptr ss:[rsp+20]                |
    00007FF63C1014EB | 48 C7 45 00 FE FF FF FF  | mov qword ptr ss:[rbp],FFFFFFFFFFFFFFFE      |
    00007FF63C1014F3 | 8B 05 5F 5E 88 00        | mov eax,dword ptr ds:[7FF63C987358]          |
    00007FF63C1014F9 | 8B 0D 01 3F 88 00        | mov ecx,dword ptr ds:[7FF63C985400]          |
    00007FF63C1014FF | 65 48 8B 14 25 58 00 00  | mov rdx,qword ptr gs:[58]                    |
    00007FF63C101508 | 48 8B 0C CA              | mov rcx,qword ptr ds:[rdx+rcx*8]             |
    00007FF63C10150C | 3B 81 04 00 00 00        | cmp eax,dword ptr ds:[rcx+4]                 |
    00007FF63C101512 | 7F 60                    | jg sublime_merge.7FF63C101574                |
    00007FF63C101514 | 48 8D 05 25 5E 88 00     | lea rax,qword ptr ds:[7FF63C987340]          | rax:&"license_window", 7FF63C987340:&"license_window"
    00007FF63C10151B | 48 89 05 3E 5E 88 00     | mov qword ptr ds:[7FF63C987360],rax          | rax:&"license_window"
    00007FF63C101522 | 66 C7 05 3D 5E 88 00 00  | mov word ptr ds:[7FF63C987368],0             | <-- patch this to 1
    00007FF63C10152B | C7 05 37 5E 88 00 00 00  | mov dword ptr ds:[7FF63C98736C],0            |
    00007FF63C101535 | B8 0F 00 00 00           | mov eax,F                                    |
    00007FF63C10153A | 66 48 0F 6E C0           | movq xmm0,rax                                | rax:&"license_window"
    00007FF63C10153F | 66 0F 73 F8 08           | pslldq xmm0,8                                |
    00007FF63C101544 | F3 0F 7F 05 34 5E 88 00  | movdqu xmmword ptr ds:[7FF63C987380],xmm0    |

Changing `mov word ptr ds:[7FF63C987368],0` to `mov word ptr ds:[7FF63C987368],1` solves it.
This seems to be the place that sets the default value tho, not sure where it overwrites it with a real license.

**Comment by bousqi** [comment]
Interesting, I'll try to have a look at this issue and proposed solution... 
Thanks @tostercx for your investiguations

**Comment by deyixtan** [comment]
@darkred @bousqi, here you go.
## Build 1065
### Windows 64-bit
| Name                              | Offset     | Original | Patched  |
| --------------------------- | --------- | --------- | --------- |
| Persistent License Check | 0x20BFD | 0x00      | 0x01      |
| Initial License Check        | 0x21915 | 0x38      | 0x08      |
|                                         | 0x21916 | 0x00      | 0x01      |

**Comment by darkred** [comment]
@deyixtan Thank you! This works great!

**Comment by tostercx** [comment]
@darkred for the theme search for "license_window", should have 1 exact match.
Scroll up a bit, the function before it should have the two movs:

    00007FF63A7A230A | mov word ptr ds:[7FF63B04BB28],0             |
    00007FF63A7A2313 | mov dword ptr ds:[7FF63B04BB2C],0            |

The first one is for the theme. In build 1070 it's

    0x22311: 00 -> 01

**Comment by deyixtan** [comment]
@tostercx the patcher was made for sublime text. I assume the byte pattern don't work for sublime merge at all. 

@bousqi, I suggest creating a separate byte pattern for this, based on the current working offsets and update the python script.

**Comment by tostercx** [comment]
@deyixtan oh, now it makes sense ^^;

**Comment by bousqi** [comment]
> @bousqi, I suggest creating a separate byte pattern for this, based on the current working offsets and update the python script.

A little bit out of time later these days. But I just got a pull request from @tostercx .
I also have to rework to pattern for linux, it no longer working for later version.

**Comment by bousqi** [comment]
Finally, patch works fine on linux 1070 ...
