### ISSUE TITLE
Patch for macOS

### ISSUE THREAD

**Issue by bt** [bousqi/slm-patcher#3]

**Comment by tostercx** [comment]
Which version is that for?

On 1065 I think it's:

    0x20139 0x38 -> 0x08
    0x2013A 0x00 -> 0x01
    0x234E5 0x00 -> 0x01

(not tested)

**Comment by tostercx** [comment]
And yet the dot somehow draws even more attention ^^;

**Comment by bt** [comment]
@tostercx haha, thanks for the offsets -- I didn't want the issue to show up on searches :)
